Update 6.1-using-word-embeddings.ipynb
On running the cell under "Putting it all together:  from raw text to word embeddings", the kernel throws the following error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1757: character maps to <undefined>

This is because the dataset stored at the link provided doesn't encode files in the utf8 format, specifying that as a parameter when opening the files prevents this error.